spring:
  application:
    name: server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

encrypt:
#  key: ${ENCRYPTION_KEY} # AES Encryption
  key-store: # RSA Encryption
    location: config-server.jks
    password: ${ENCRYPTION_PASSWORD}
    alias: config-server-key
