spring:
  application:
    name: server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hstha/app-configuration

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

encrypt:
#  key: ${ENCRYPTION_KEY} # AES Encryption
  key-store: # RSA Encryption
    location: config-server.jks
    password: ${ENCRYPTION_PASSWORD}
    alias: config-server-key